import type { Metadata, Viewport } from "next";
import "highlight.js/styles/dark.min.css";
import "./globals.css";
import Navigation from "@/components/layouts/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  colorScheme: "dark",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="container mx-auto my-0 flex flex-col gap-8 lg:flex-row lg:gap-12">
        <Navigation />
        {children}
      </body>
    </html>
  );
}
